language: python
python:
  - "3.10"
env:
  - WAGTAIL="wagtail==4.1.1" DB=sqlite
services:
  - mysql
  - postgresql
addons:
  postgresql: "13"
before_script:
  - mysql -e 'create database wagtail_modeltranslation;'
  - psql -c 'create database wagtail_modeltranslation;' -U postgres
install:
  - pip install --upgrade -q pip setuptools
  - if [[ $DB == mysql ]] && [[ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]]; then pip install -q mysql-python; elif [[ $DB == mysql ]] && [[ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]]; then pip install -q mysqlclient; fi
  - if [[ $DB == postgres ]]; then pip install -q 'psycopg2-binary'; fi
  - pip install $WAGTAIL
  - pip install -e .
script:
  - echo "DJANGO VERSION = `python -m django --version`"
  - ./runtests.py
